import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/header";
import SectionContainer from "@/app/components/section_container";

export const metadata: Metadata = { title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body className="bg-white text-black antialiased dark:bg-gray-950 dark:text-white">
    <SectionContainer >
    <div className="flex h-screen flex-col justify-between font-sans">
        <Header/>
        <main className="mb-auto">{children}</main>
    </div>
    </SectionContainer>
    </body>
    </html>
  );
}
