# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
        - 'sc_blog_next/**'
  pull_request:
    branches: [ "main" ]
    paths:
        - 'sc_blog_next/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn
        cache-dependency-path: ./sc_blog_next/package-lock.json
    - run: npm ci
      working-directory: sc_blog_next
    - run: npm run build --if-present
      working-directory: sc_blog_next
    - run: npm test
      working-directory: sc_blog_next

